version: '3.1'
services:

    webserver:
        container_name: nginx
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        container_name: php_fpm
        build: deploy/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './deploy/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    
    graphdb:
        container_name: neo_4j
        image: neo4j:latest
        env_file:
            - .env 
        volumes:
            - ./docker-data/neo4j/data:/data      
            - ./docker-data/neo4j/logs:/logs      
            - ./docker-data/neo4j/plugins:/plugins 
        environment:
            - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
            - NEO4J_server_config_strict__validation_enabled=${NEO4J_server_config_strict__validation_enabled}
        ports:
            - 7474:7474
            - 7687:7687
    
    sqldb:
        container_name: mariadb
        image: mariadb:10
        env_file:
            - .env 
        volumes:
            - ./docker-data/mariadb/backup-volume:/backup
            - ./docker-data/neo4j:/data      
        environment:
            - MYSQL_DATABASE=${MYSQL_INITIAL_DATABASE}
            - MYSQL_USER=${MYSQL_INITIAL_USER}
            - MYSQL_PASSWORD=${MYSQL_INITIAL_PASSWORD}
            - MYSQL_RANDOM_ROOT_PASSWORD=${USE_MYSQL_INITIAL_RANDOM_ROOT_PASSWORD}
        ports:
            - 3306:3306
